### PR TITLE
v8.1 noarch 

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@ocefpaf looks like requests needs to be updated in order to allow for libcurl>=7.64

**Comment by doutriaux1** [comment]
@jarifibrahim @kalefranz @mcg1969 @mingwandroid @msarahan @pelson @sigmavirus24 @carlodri pinging you guys as well on this.

**Comment by doutriaux1** [comment]
nevermind it comes straight form libcurl that requires openssl lower

**Comment by ocefpaf** [comment]
I believe that these issues will be solved once we start migrating the stack to the latest `openssl`. Not sure what is the status on that, maybe @CJ-Wright can comment on that.

**Comment by CJ-Wright** [comment]
There is an open PR into the pinning repo no one seems to have merged it though.
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/191

**Comment by ocefpaf** [comment]
> There is an open PR into the pinning repo no one seems to have merged it though.
> [conda-forge/conda-forge-pinning-feedstock#191](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/191)

Done :grimacing:

**Pull request merged**
